import type { FieldMapping, MappingFieldDef, MappingGroup } from "./types";

// ── Existing v2 Constants ───────────────────────────────────────────────────

export const IMPORT_PAGE_PATTERNS = [
  "https://app.treez.io/treez-admin/import/home*",
  "https://app.sandbox.treez.io/treez-admin/import/home*",
  "https://app.dev.treez.io/treez-admin/import/home*",
];

export const STEP_LABELS = ["Upload", "Map", "Review", "Import"] as const;

// ── POS Systems ─────────────────────────────────────────────────────────────

export const POS_SYSTEMS = [
  "Blaze",
  "Cova",
  "Dutchie",
  "Flowhub",
  "IndicaOnline",
  "Meadow",
] as const;

// ── Mapping Groups ──────────────────────────────────────────────────────────

export const MAPPING_GROUPS: MappingGroup[] = [
  "Product Info",
  "Cannabis Details",
  "Pricing",
  "Attributes",
  "Display & Media",
];

// ── Unified Mapping Fields ──────────────────────────────────────────────────

export const MAPPING_FIELDS: MappingFieldDef[] = [
  // Product Info
  {
    key: "productIdentifier",
    label: "Product ID / SKU",
    description: "Unique ID per product (e.g. SKU, Product ID)",
    group: "Product Info",
  },
  {
    key: "productName",
    label: "Product Name",
    description: "Name of the product",
    group: "Product Info",
    required: true,
  },
  { key: "brand", label: "Brand", description: "Brand name", group: "Product Info" },
  {
    key: "productCategory",
    label: "Product Category",
    description: "Product category or Product type",
    group: "Product Info",
    required: true,
  },
  {
    key: "productSubCategory",
    label: "Subcategory",
    description: "Product subcategory or subtype",
    group: "Product Info",
  },
  {
    key: "status",
    label: "Status",
    description: "Active status or retired flag",
    group: "Product Info",
  },
  {
    key: "description",
    label: "Description",
    description: "Product description",
    group: "Product Info",
  },

  // Cannabis Details
  { key: "strain", label: "Strain", description: "Strain name", group: "Cannabis Details" },
  {
    key: "classification",
    label: "Classification",
    description: "Sativa, Indica, Hybrid, etc.",
    group: "Cannabis Details",
  },
  {
    key: "weight",
    label: "Weight / Amount",
    description: "Product weight (e.g. 0.5g, 500mg)",
    group: "Cannabis Details",
    required: true,
  },
  {
    key: "thc",
    label: "THC Content",
    description: "Manufactured Goods - THC Content (mg)",
    group: "Cannabis Details",
  },
  {
    key: "cbd",
    label: "CBD Content",
    description: "CBD value (%, mg, or mg/g)",
    group: "Cannabis Details",
  },

  // Pricing
  {
    key: "basePrice",
    label: "Price",
    description: "Product price",
    group: "Pricing",
    required: true,
  },
  {
    key: "priceTier",
    label: "Price Tier",
    description: "Price profile / tier name",
    hidden: true,
    group: "Pricing",
  },
  {
    key: "priceType",
    label: "Price Type",
    description: "Price type (MED, REC, BOTH)",
    hidden: true,
    group: "Pricing",
  },

  // Attributes
  {
    key: "tags",
    label: "Internal Tags",
    description: "Internal-only product tags (not visible to customers)",
    group: "Attributes",
  },
  {
    key: "effects",
    label: "Effects",
    description: "Product effects attribute",
    group: "Attributes",
  },
  { key: "flavor", label: "Flavor", description: "Flavor attribute", group: "Attributes" },
  {
    key: "ingredients",
    label: "Ingredients",
    description: "Ingredients attribute",
    group: "Attributes",
  },

  // Display & Media
  {
    key: "menuTitle",
    label: "Menu / Online Title",
    description: "Display name on menu",
    group: "Display & Media",
  },
  {
    key: "availableOnline",
    label: "Available Online",
    description: "Whether visible on online menu",
    group: "Display & Media",
  },
  {
    key: "imageFilename",
    label: "Image",
    description: "Image filename or URL fragment",
    group: "Display & Media",
  },
  {
    key: "externalCategory",
    label: "External Category",
    description: "Additional category info used for category resolution",
    hidden: true,
    group: "Display & Media",
  },
  {
    key: "variantIdentifier",
    label: "Variant ID",
    description: "Variant ID for composite key",
    hidden: true,
    group: "Display & Media",
  },
];

export function createEmptyMappings(): FieldMapping[] {
  return MAPPING_FIELDS.map((f) => ({
    fieldKey: f.key,
    label: f.label,
    sourceHeader: null,
  }));
}

// ── Per-POS Default Column Mappings ─────────────────────────────────────────

export const POS_DEFAULTS: Record<string, Record<string, string>> = {
  Dutchie: {
    productIdentifier: "SKU",
    productName: "Product",
    brand: "Brand",
    productCategory: "Category",
    externalCategory: "External category",
    status: "Is retired",
    strain: "Strain",
    classification: "Strain Type",
    weight: "Product grams",
    basePrice: "Price",
    description: "Online description",
    menuTitle: "Online title",
    availableOnline: "Is available online",
    imageFilename: "Image URL",
    tags: "Tags",
    flavor: "Flavor",
    ingredients: "Ingredients",
    thc: "THC content",
    cbd: "CBD content",
  },
  Blaze: {
    productIdentifier: "Product ID",
    productName: "Item",
    brand: "Brand",
    productCategory: "Category",
    productSubCategory: "Cannabis Type",
    externalCategory: "Custom Weight Type",
    status: "Active",
    strain: "Genetics",
    classification: "Type",
    weight: "Custom Weight Measurement",
    basePrice: "Unit Price",
    description: "Description",
    availableOnline: "Available Online",
    imageFilename: "Image 1",
    tags: "Tag",
    cbd: "CBD %",
  },
  Flowhub: {
    productIdentifier: "Product Id",
    productName: "Product Name",
    brand: "Brand",
    productCategory: "Category",
    productSubCategory: "Product Type",
    externalCategory: "Variant Type",
    strain: "Strain Name",
    classification: "Strain Species",
    weight: "Weight / Volume",
    basePrice: "Price",
    description: "Description",
    thc: "Mg THC",
    cbd: "Mg CBD",
    variantIdentifier: "Variant Id",
    priceTier: "Price Profile",
    priceType: "Price Type",
  },
  IndicaOnline: {
    productIdentifier: "Product ID",
    productName: "Product Name",
    brand: "Brand",
    productCategory: "Parent Category",
    productSubCategory: "Sub-category (L2)",
    externalCategory: "Sub-category (L3)",
    strain: "Strain Type",
    weight: "Net Weight",
    basePrice: "Price per Unit",
    tags: "Tags",
  },
  Meadow: {
    productIdentifier: "ID",
    productName: "Product Name",
    brand: "Brand",
    productCategory: "Primary Category",
    productSubCategory: "Sub Categories",
    status: "Active",
    strain: "Strain Type",
    weight: "Cannabis Content",
    basePrice: "Price",
    description: "Description",
    availableOnline: "Menu Status Online",
    thc: "THC Content",
    cbd: "CBD Content",
  },
  Cova: {
    productIdentifier: "Manufacturer SKU",
    productName: "Model Name *",
    brand: "Brands",
    productCategory: "Classification *",
    externalCategory: "Reporting Category",
    status: "Product Status",
    strain: "Strain",
    classification: "Short Description",
    weight: "Net Weight",
    basePrice: "Price",
    description: "Long Description",
    imageFilename: "Hero Shot URI",
    thc: "THC Content",
    cbd: "CBD %",
  },
};

export const MAX_FILE_SIZE = 100 * 1024 * 1024; // 100MB

// ── Product Categories (Phase 3 readiness) ──────────────────────────────────

export const PRODUCT_CATEGORIES = [
  "Beverage",
  "CBD",
  "Cartridge",
  "Edible",
  "Extract",
  "Flower",
  "Merch",
  "Misc",
  "Non-Inv",
  "Pill",
  "Plant",
  "Preroll",
  "Tincture",
  "Topical",
] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];

// ── Product Sub-Categories (keyed by category) ──────────────────────────────

export const PRODUCT_SUBCATEGORIES: Record<string, string[]> = {
  Beverage: [
    "Beer",
    "Beverage - General",
    "Coffee",
    "Dissolvable",
    "Elixir",
    "Juice",
    "Other",
    "Seltzer",
    "Shot",
    "Soda",
    "Tea",
    "Tonic",
    "Water",
  ],
  CBD: [
    "Beverage",
    "CBD - General",
    "Cartridge",
    "Edible",
    "Extract",
    "Oil",
    "Pill",
    "Tincture",
    "Topical",
  ],
  Cartridge: [
    "510 Thread",
    "All In One",
    "CCELL",
    "Cartridge - General",
    "Cured Resin",
    "Diamond",
    "Distillate",
    "Full Spectrum",
    "Hash",
    "Live Resin",
    "Other",
    "Pax",
    "Pax Pod",
    "Pod",
    "Ready To Use",
    "Rosin",
  ],
  Edible: [
    "Baked Good",
    "Butter",
    "Capsule",
    "Chew",
    "Chocolate",
    "Cookie",
    "Edible - General",
    "Gum",
    "Gummy",
    "Hard Candy",
    "Honey",
    "Lozenge",
    "Mints",
    "Oil",
    "Other",
    "Savory",
    "Sublingual",
    "Sublingual Tablet",
    "Tablingual",
  ],
  Extract: [
    "Badder",
    "Bubble Hash",
    "Budder",
    "Bulk Extract",
    "Caviar",
    "Crumble",
    "Crystalline",
    "Cured Resin",
    "Diamonds",
    "Distillate",
    "Dry Sift",
    "Extract - General",
    "Flower Rosin",
    "Full Spectrum Oil",
    "Hash",
    "Hash Rosin",
    "Ice Water Hash",
    "Isolate",
    "Jam",
    "Jelly",
    "Kief",
    "Live Resin",
    "Live Resin Badder",
    "Live Resin Budder",
    "Live Resin Sauce",
    "Live Resin Sugar",
    "Live Rosin",
    "Moon Rocks",
    "Oil",
    "Other",
    "Powder Hash",
    "RSO",
    "Rosin",
    "Rosin Budder",
    "Rosin Sauce",
    "Sauce",
    "Shatter",
    "Sift Rosin",
    "Sugar",
    "THC-A",
    "Temple Ball",
    "Temple Ball Hash",
    "Water Hash",
    "Wax",
  ],
  Flower: [
    "Bulk Flower",
    "Flower - General",
    "Infused Flower",
    "Kief",
    "Pre-Ground",
    "Pre-Pack",
    "Pre-Pack Shake",
    "Pre-Pack Smalls",
    "Shake",
    "Strain Specific Shake",
  ],
  Merch: [
    "Accessory",
    "Apparel",
    "Battery",
    "Beverage",
    "Bong",
    "Book",
    "Dab Rig",
    "Gift Card",
    "Grinder",
    "Hat",
    "Hoodie",
    "Lighter",
    "Merch - General",
    "Other",
    "Pipe",
    "Rolling Papers",
    "Snack",
    "Sweatshirt",
    "T Shirt",
    "Vaporizer",
  ],
  Misc: ["Bath", "Liquid", "Misc - General", "Other", "Solid", "Suppository"],
  "Non-Inv": ["Fee", "Gift Card", "Membership", "Non-Inv - General", "Other"],
  Pill: ["Capsule", "Chewable", "Other", "Pill - General", "Tablet"],
  Plant: ["Clone", "Fresh Whole Plant", "Plant - General", "Seeds", "Teen"],
  Preroll: ["Blunt", "Flower", "Infused", "Infused Blunt", "Preroll - General", "Shake"],
  Tincture: ["Dropper", "Other", "Sauce", "Spray", "Syrup", "Tincture", "Tincture - General"],
  Topical: [
    "Balm",
    "Cosmetic",
    "Cream",
    "Gel",
    "Lotion",
    "Lubricant",
    "Oil",
    "Other",
    "Patch",
    "Roll-On",
    "Salve",
    "Spray",
    "Topical - General",
  ],
};

// ── UoM by Category ─────────────────────────────────────────────────────────

export const EACH_UOM_CATEGORIES = new Set(["Merch", "Non-Inv", "Plant"]);

export const UOM_BY_CATEGORY: Record<string, string> = {
  Cartridge: "grams",
  Extract: "grams",
  Flower: "grams",
  Preroll: "grams",
  Beverage: "milligrams",
  CBD: "milligrams",
  Edible: "milligrams",
  Misc: "milligrams",
  Pill: "milligrams",
  Tincture: "milligrams",
  Topical: "milligrams",
  Merch: "each",
  "Non-Inv": "each",
  Plant: "each",
};

// ── Classification Values ───────────────────────────────────────────────────

export const VALID_CLASSIFICATIONS = ["Sativa", "Indica", "Hybrid", "I/S", "S/I", "CBD"] as const;
